name: Chromatic docs

on:
  push:
    branches:
      - main

jobs:
  vet:
    name: vet
    runs-on: ubuntu-latest
    if: "${{ startsWith(github.event.head_commit.message, 'chore: publish') }}"
    env:
      CI: true
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
          registry-url: https://registry.npmjs.org/

      - name: Bootstrap
        run: yarn bootstrap

      - name: Vet
        run: yarn vet

  publishDevStoryBook:
    name: dev storybook
    needs: vet
    environment: DEV
    runs-on: ubuntu-latest
    if: "${{ startsWith(github.event.head_commit.message, 'chore: publish patch') }}"
    env:
      CI: true
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_GITHUB  }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
          registry-url: https://registry.npmjs.org/

      - name: Bootstrap
        run: yarn bootstrap

      - name: Build
        run: yarn build

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  publishProdStoryBook:
    name: prod storybook
    needs: vet
    environment: PROD
    runs-on: ubuntu-latest
    if: "${{ startsWith(github.event.head_commit.message, 'chore: publish m') }}"
    env:
      CI: true
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_GITHUB  }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
          registry-url: https://registry.npmjs.org/

      - name: Bootstrap
        run: yarn bootstrap

      - name: Build
        run: yarn build

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}