name: Main

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@badatt'

      - name: Install Dependencies
        run: yarn

      - name: Spellcheck
        run: yarn spellcheck

      - name: Build
        run: yarn build

      - name: Publish to Github
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@badatt'

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
