name: Main

on:
  push:
    branches:
      - main

jobs:
  npm-package-release:
    name: Npm package release
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org/
          scope: "@badatt"

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Publish to Npm registry
        run: |
          yarn release
