name: Pull request checks & lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - 'release/**'

jobs:
  vetTestCoverage:
    name: vet, test & coverage
    runs-on: ubuntu-latest
    env:
      CI: true
      FORCE_COLOR: true
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
          registry-url: https://registry.npmjs.org/

      - name: Bootstrap
        run: yarn bootstrap

      - name: Vet
        run: yarn vet

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
        env:
          FORCE_COLOR: true

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
