name: Publish packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: publish packages
    runs-on: ubuntu-latest
    if: "${{ !startsWith(github.event.head_commit.message, 'chore: publish') }}"
    env:
      CI: true
      FORCE_COLOR: true
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_GITHUB  }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
          registry-url: https://registry.npmjs.org/
          always-auth: false

      - name: Bootstrap
        run: yarn bootstrap

      - name: Vet
        run: yarn vet

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Configure Git User
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Release patch version
        if: "${{ !startsWith(github.event.head_commit.message, 'chore: release') }}"
        run: yarn release:patch
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB  }}

      - name: Release minor version
        if: "${{ startsWith(github.event.head_commit.message, 'chore: release minor') }}"
        run: yarn release:minor
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB  }}

      - name: Release major version
        if: "${{ startsWith(github.event.head_commit.message, 'chore: release major') }}"
        run: yarn release:major
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB  }}

      - name: Publish to NPM
        run: npm run publish:npm
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB  }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
