name: Publish packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: publish packages
    runs-on: ubuntu-latest
    if: "${{ !startsWith(github.event.head_commit.message, 'chore: publish') }}"
    env:
      CI: true
      FORCE_COLOR: true
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check out the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.x'
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: yarn bootstrap

      - name: Vet
        run: yarn vet

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Configure Git User
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Publish patch version
        if: "${{ !startsWith(github.event.head_commit.message, 'chore: release') }}"
        run: "npx lerna publish patch -m 'chore: publish patch %s' --conventional-commits --create-release github -y"
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB  }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish minor version
        if: "${{ startsWith(github.event.head_commit.message, 'chore: release minor') }}"
        run: "npx lerna publish minor -m 'chore: publish minor %s' --force-publish --conventional-commits --create-release github -y"
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB  }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish major version
        if: "${{ startsWith(github.event.head_commit.message, 'chore: release major') }}"
        run: "npx lerna publish major -m 'chore: publish major %s' --force-publish --conventional-commits --create-release github -y"
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB  }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
